// Package integration defines provider-neutral capability seams used by
// agent tools (filesystem, subprocess, web). The agent core depends only on
// these interfaces; concrete bound environments (local host or remote
// execution) implement them outside the core.
package integration

import (
	"context"
	"errors"
	"time"
)

// Target is a resolved, sandbox-safe path. Implementations perform path
// resolution against their own root/cwd and prevent escapes.
type Target struct {
	// Key is the provider-owned identity used for observation and CAS. It is
	// deliberately not model-facing and must not be parsed outside a provider.
	Key string
	// Path is the provider execution path. New callers should display
	// DisplayPath instead; Path remains for provider compatibility.
	Path string
	// DisplayPath is the canonical workspace-relative path safe for models/UI.
	DisplayPath string
}

// FileVersion is an opaque freshness token. Callers may only pass a value
// returned by this contract back to a guarded operation; it is never a path,
// workspace revision, event cursor, or a value intended for UI interpretation.
type FileVersion string

type FileKind string

const (
	FileKindUnknown   FileKind = "unknown"
	FileKindFile      FileKind = "file"
	FileKindDirectory FileKind = "directory"
	FileKindSymlink   FileKind = "symlink"
	FileKindOther     FileKind = "other"
)

// FileInfo describes a resolved target without exposing host-specific types.
type FileInfo struct {
	Exists  bool
	IsDir   bool
	Size    int64
	Version FileVersion // content version for CAS (hash or mtime-based)
	Kind    FileKind
}

// TextRead is one coherent regular-text read. Content and Version describe
// the same byte snapshot; callers must not compose a model observation from a
// separate Stat followed by ReadText when this capability is available.
type TextRead struct {
	Content string
	Version FileVersion
	Size    int64
}

// VersionedTextFileSystem avoids the Stat-then-read race and duplicate full
// reads for providers that can return content and its freshness token together.
type VersionedTextFileSystem interface {
	ReadTextVersioned(ctx context.Context, target Target, maxBytes int64) (TextRead, error)
}

type WriteIntentKind string

const (
	// WriteIntentCreateIfAbsent atomically creates a target only if it does not
	// already exist.
	WriteIntentCreateIfAbsent WriteIntentKind = "create_if_absent"
	// WriteIntentReplaceIfVersion atomically replaces a target only if its
	// current opaque version equals Version.
	WriteIntentReplaceIfVersion WriteIntentKind = "replace_if_version"
)

// WriteIntent controls write semantics. Model-facing tools must use one of
// the constructors below. Deprecated fields are retained only to keep older
// host adapters source-compatible during the v8 hard cutover; providers
// normalize them at their boundary and never expose them to the model.
type WriteIntent struct {
	Kind    WriteIntentKind
	Version FileVersion

	// ExpectedVersion, when non-empty, enables optimistic concurrency: the
	// write succeeds only if the current version matches (CAS guard).
	ExpectedVersion string
	// CreateIfAbsent fails the write if the file already exists.
	CreateIfAbsent bool
	// Overwrite guards full-content replaces; conservative default.
	Overwrite bool
}

func CreateIfAbsentIntent() WriteIntent { return WriteIntent{Kind: WriteIntentCreateIfAbsent} }

func ReplaceIfVersionIntent(version FileVersion) WriteIntent {
	return WriteIntent{Kind: WriteIntentReplaceIfVersion, Version: version}
}

// Normalized returns the explicit v2 intent. The boolean fields are accepted
// only for persisted/pre-v8 callers and must not be generated by new tools.
func (i WriteIntent) Normalized() (WriteIntentKind, FileVersion, error) {
	if i.Kind != "" {
		switch i.Kind {
		case WriteIntentCreateIfAbsent:
			return i.Kind, "", nil
		case WriteIntentReplaceIfVersion:
			if i.Version == "" {
				return "", "", ErrStaleVersion
			}
			return i.Kind, i.Version, nil
		default:
			return "", "", NewFSError(FSInvalidPath, false, "use a supported write intent", nil)
		}
	}
	if i.CreateIfAbsent {
		return WriteIntentCreateIfAbsent, "", nil
	}
	if i.Overwrite && i.ExpectedVersion != "" {
		return WriteIntentReplaceIfVersion, FileVersion(i.ExpectedVersion), nil
	}
	return "", "", NewFSError(FSNotObserved, false, "read the file before replacing it", ErrNotObserved)
}

// WriteResult reports the outcome of a write.
type WriteResult struct {
	Version FileVersion
	// Created is true when a new file was created.
	Created bool
}

// EditRequest is a literal, targeted replacement (old_string must match).
type EditRequest struct {
	OldString string
	NewString string
	// ReplaceAll replaces every occurrence instead of requiring uniqueness.
	ReplaceAll bool
}

// EditIntent mirrors WriteIntent for CAS on edits.
type EditIntent struct {
	ExpectedVersion FileVersion
}

// EditResult reports the edit outcome.
type EditResult struct {
	Version   FileVersion
	Replaced  int
	OldString string
	NewString string
}

// FileSystem is the provider-neutral filesystem seam. Local and remote
// implementations satisfy it; tools never know which is active.
type FileSystem interface {
	// Resolve binds a raw path against cwd and returns a sandbox-safe Target.
	Resolve(ctx context.Context, rawPath, cwd string) (Target, error)
	// Stat returns metadata for a resolved target.
	Stat(ctx context.Context, target Target) (FileInfo, error)
	// ReadText returns the file content.
	ReadText(ctx context.Context, target Target) (string, error)
	// WriteText creates or replaces a file with CAS support.
	WriteText(ctx context.Context, target Target, content string, intent WriteIntent) (WriteResult, error)
	// EditText performs a targeted replacement with CAS support.
	EditText(ctx context.Context, target Target, edit EditRequest, intent EditIntent) (EditResult, error)
	// Delete removes an observed file only when its version still matches.
	Delete(ctx context.Context, target Target, expectedVersion FileVersion) (DeleteResult, error)
}

type DeleteResult struct {
	Deleted bool
}

// BinaryFileSystem is the optional media extension used by read_image. Text
// adapters may omit it and fail closed rather than decoding arbitrary bytes.
type BinaryFileSystem interface {
	ReadBytes(ctx context.Context, target Target) ([]byte, error)
}

// Observation is the per-owner visibility state of a target
// (H-FS-OBS-001..006): unseen, absent, or present with a content version.
type Observation int

const (
	// ObservationUnseen means the session has not read the target.
	ObservationUnseen Observation = iota
	// ObservationAbsent means the session observed the target missing.
	ObservationAbsent
	// ObservationPresent means the session read the target and knows a version.
	ObservationPresent
)

// GrepMatch is one content-search hit (path-relative, 1-based line number).
type GrepMatch struct {
	Path string
	Line int
	Text string
}

// SearchFileSystem is the optional content-search extension of FileSystem
// (glob/grep tools). Implementations search inside their containment root,
// return deterministic results, and never build shell commands from patterns
// (H-PROC-003).
type SearchFileSystem interface {
	// Glob lists files under dir matching pattern (deterministic, bounded).
	Glob(ctx context.Context, dir, pattern string, maxResults int) ([]string, error)
	// Grep scans regular text files under dir; maxMatches bounds results.
	Grep(ctx context.Context, dir, pattern string, maxMatches int, maxBytesPerFile int64) ([]GrepMatch, error)
}

// ObservationRecorder is the optional observation extension of FileSystem.
// Tools enforce read-before-edit through it (H-EDIT-004): an edit against an
// unobserved target is refused unless the recorder exists and the target was
// observed. Observations are scoped per owner (session/agent) and never leak
// between users (H-FS-OBS-007).
type ObservationRecorder interface {
	// Observe records the observation of a target for an owner.
	Observe(ctx context.Context, target Target, owner string, state Observation, version FileVersion) error
	// Observed returns the recorded state, content version and whether the
	// target has been observed at all.
	Observed(ctx context.Context, target Target, owner string) (Observation, FileVersion, bool)
}

// FSError is the stable provider-neutral error exposed to retry/UI policy.
// Its technical cause stays server-side through Unwrap and must not drive UI
// branching.
type FSError struct {
	Code      FSErrorCode
	Retryable bool
	RetryHint string
	Cause     error
}

func (e *FSError) Error() string {
	if e.Cause != nil {
		return string(e.Code) + ": " + e.Cause.Error()
	}
	return string(e.Code)
}
func (e *FSError) Unwrap() error { return e.Cause }

func NewFSError(code FSErrorCode, retryable bool, hint string, cause error) *FSError {
	return &FSError{Code: code, Retryable: retryable, RetryHint: hint, Cause: cause}
}

type FSErrorCode string

const (
	FSInvalidPath        FSErrorCode = "FS_INVALID_PATH"
	FSNotFound           FSErrorCode = "FS_NOT_FOUND"
	FSNotDirectory       FSErrorCode = "FS_NOT_DIRECTORY"
	FSNotText            FSErrorCode = "FS_NOT_TEXT"
	FSNotRegularFile     FSErrorCode = "FS_NOT_REGULAR_FILE"
	FSTooLarge           FSErrorCode = "FS_TOO_LARGE"
	FSPermissionDenied   FSErrorCode = "FS_PERMISSION_DENIED"
	FSSandboxDenied      FSErrorCode = "FS_SANDBOX_DENIED"
	FSParentCreateFailed FSErrorCode = "FS_PARENT_CREATE_FAILED"
	FSIO                 FSErrorCode = "FS_IO_ERROR"
	FSStaleVersion       FSErrorCode = "FS_STALE_VERSION"
	FSNotObserved        FSErrorCode = "FS_NOT_OBSERVED"
	FSAmbiguousEdit      FSErrorCode = "FS_AMBIGUOUS_EDIT"
	FSEditNotFound       FSErrorCode = "FS_EDIT_NOT_FOUND"
	FSAborted            FSErrorCode = "FS_ABORTED"
	FSAlreadyExists      FSErrorCode = "FS_ALREADY_EXISTS"
	FSOutcomeUnknown     FSErrorCode = "TOOL_OUTCOME_UNKNOWN"
)

// Sentinel errors returned by FileSystem implementations.
var (
	ErrNotObserved       = errors.New("file was not read before edit (read the file, then retry)")
	ErrStaleVersion      = errors.New("file version changed since it was read (re-read, then retry)")
	ErrAlreadyExists     = errors.New("file already exists (createIfAbsent)")
	ErrAmbiguousMatch    = errors.New("old_string matched more than once (use replace_all or a more specific match)")
	ErrTargetOutsideRoot = errors.New("resolved target escapes the sandbox root")
)

// Subprocess is the provider-neutral command execution seam.
type Subprocess interface {
	// Run executes a command and returns combined output. workdir is required
	// (commands are stateless shell processes; do not rely on cd).
	Run(ctx context.Context, cmd Command) (Result, error)
}

// Command is a provider-neutral command request.
type Command struct {
	// Command is the full command line (e.g. "pnpm test").
	Command string
	// Description is human-readable, for telemetry/approvals.
	Description string
	// Workdir is the working directory (required; commands do not share state).
	Workdir string
	// Timeout bounds execution; zero uses the provider default.
	Timeout time.Duration
}

// Result is a completed command outcome.
type Result struct {
	ExitCode int
	Output   string
	TimedOut bool
	// JobID is set when the command ran in the background.
	JobID string
}
